version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # This image needs to match our 'target' sdk version. The 'alpha' designation
      # _is_ kinda weird, but the images generally work just fine.
      - image: circleci/android:api-28-alpha
    environment:
      # Gradle treats JVM_OPTS with lower precedence than JAVA_OPTS,
      # according to https://circleci.com/blog/how-to-handle-java-oom-errors/
      #
      # We use a relatively low number for max memory, as that is what 
      # https://discuss.circleci.com/t/circleci-2-0-android-with-kotlin/17531/2
      # recommends.
      #
      JAVA_OPTS: -Xmx1000m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build debug APK and release APK
          command: ./gradlew assembleDebug -Pbuild_number=$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apks
